version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: next_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123!
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - next
  
  redis:
    image: redis:7
    container_name: next_redis
    environment:
      REDIS_PASSWORD: admin123!
    command: ["redis-server", "--requirepass", "admin123!"]
    ports:
      - "6379:6379"
    networks:
      - next
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:

networks:
  next:
